# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.URLField(max_length=2000, unique=True)),
                ('is_external', models.BooleanField(default=False)),
                ('categories', taggit.managers.TaggableManager(
                    blank=True,
                    help_text='A comma-separated list of tags.',
                    through='taggit.TaggedItem',
                    to='taggit.Tag',
                    verbose_name='Tags')),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='users.User')),
            ],
        ),
    ]
