# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_linkusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkusage',
            name='link',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='usage',
                to='links.Link'
            ),
        ),
    ]
