# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20160216_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='categories',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags'
            ),
        ),
        migrations.AlterField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='users.User'
            ),
        ),
    ]
