# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20160216_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
