# -*- coding: utf-8 -*-
# (c) Crown Owned Copyright, 2016. Dstl.
# Generated by Django 1.9.1 on 2016-02-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('fullName', models.CharField(max_length=256)),
                ('phone', models.CharField(
                    blank=True,
                    max_length=256,
                    null=True)),
                ('email', models.CharField(
                    blank=True,
                    max_length=256,
                    null=True)),
                ('last_login', models.DateTimeField(
                    blank=True,
                    null=True)),
            ],
        ),
    ]
