# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20160301_1616'),
        ('users', '0002_auto_20160301_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
