# -*- coding: utf-8 -*-
# (c) Crown Owned Copyright, 2016. Dstl.
# Generated by Django 1.9.1 on 2016-03-11 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='original_slug',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
