# -*- coding: utf-8 -*-
# (c) Crown Owned Copyright, 2016. Dstl.
# Generated by Django 1.9.1 on 2016-03-11 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_migrate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='original_slug',
            field=models.CharField(max_length=256),
        ),
    ]
