# -*- coding: utf-8 -*-
# (c) Crown Owned Copyright, 2016. Dstl.
# Generated by Django 1.9.1 on 2016-03-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160311_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_way_to_contact',
            field=models.CharField(
                blank=True,
                default='',
                max_length=1024,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='best_way_to_find',
            field=models.CharField(
                blank=True,
                default='',
                max_length=1024,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(
                blank=True,
                default='',
                max_length=256,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                blank=True,
                default='',
                max_length=256,
                null=True
            ),
        ),
    ]
